// The built-in agent-avatar catalog — one entry per file in public/avatars,
// kept in sync by avatars.test.ts. The server accepts exactly these paths.
export interface AvatarEntry { path: string; label: string }

const entry = (file: string, label: string): AvatarEntry => ({ path: `/avatars/${file}.svg`, label });

export const AVATARS: readonly AvatarEntry[] = [
  entry('Architect', 'Architect'),
  entry('CEO', 'CEO'),
  entry('CTO', 'CTO'),
  entry('CustomerSupport', 'Customer Support'),
  entry('DataAnalyst', 'Data Analyst'),
  entry('Designer', 'Designer'),
  entry('DevOps', 'DevOps'),
  entry('Finance', 'Finance'),
  entry('FullStackEngineer', 'Full Stack Engineer'),
  entry('GTM', 'GTM'),
  entry('HR', 'HR'),
  entry('KnowledgeKeeper', 'Knowledge Keeper'),
  entry('Legal', 'Legal'),
  entry('Marketing', 'Marketing'),
  entry('Monitor', 'Monitor'),
  entry('Operations', 'Operations'),
  entry('Orchestrator', 'Orchestrator'),
  entry('Planner', 'Planner'),
  entry('Product', 'Product'),
  entry('QAEngineer', 'QA Engineer'),
  entry('Researcher', 'Researcher'),
  entry('Reviewer', 'Reviewer'),
  entry('Sales', 'Sales'),
  entry('Security', 'Security'),
  entry('TechnicalWriter', 'Technical Writer'),
  entry('Translator', 'Translator'),
  entry('ENFJ', 'ENFJ'),
  entry('ENFP', 'ENFP'),
  entry('ENTJ', 'ENTJ'),
  entry('ENTP', 'ENTP'),
  entry('ESFJ', 'ESFJ'),
  entry('ESFP', 'ESFP'),
  entry('ESTJ', 'ESTJ'),
  entry('ESTP', 'ESTP'),
  entry('INFJ', 'INFJ'),
  entry('INFP', 'INFP'),
  entry('INTJ', 'INTJ'),
  entry('INTP', 'INTP'),
  entry('ISFJ', 'ISFJ'),
  entry('ISFP', 'ISFP'),
  entry('ISTJ', 'ISTJ'),
  entry('ISTP', 'ISTP'),
];
